export const CHAT_TOKEN = {
    LOADING: "CHAT_TOKEN_LOADING",
    SUCCESS: "CHAT_TOKEN_SUCCESS",
    FAILED: "CHAT_TOKEN_FAILED"
};
export const AUTH = {
    LOADING: "AUTH_LOADING",
    SUCCESS: "AUTH_SUCCESS",
    FAILED: "AUTH_FAILED",
    LOGOUT: "AUTH_LOGOUT"
};

export const NEW_MESSAGES = {
    LOADING: "NEW_MESSAGES_LOADING",
    SUCCESS: "NEW_MESSAGES_SUCCESS",
    FAILED: "NEW_MESSAGES_FAILED"
}
export const BOX_CHAT = {
    OPEN: "BOX_CHAT_OPEN",
    CLOSE: "BOX_CHAT_CLOSE"
}
